version: '3'
services:
  db:
    image: mysql:8.4
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  web:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    environment:
      - RAILS_ENV=development
    volumes:
      - .:/rails
    working_dir: /rails
    ports:
      - "3000:3000"
    depends_on:
      - db