version: '3'
services:
  db:
    image: postgres:16
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - RAILS_ENV=development
      - POSTGRES_PASSWORD=password
    volumes:
      - .:/rails
    working_dir: /rails
    ports:
      - "3000:3000"
    depends_on:
      - db
  css:
    build: . 
    command: bash -c "bin/rails tailwindcss:build --watch"
    environment:
      - RAILS_ENV=development
      - POSTGRES_PASSWORD=password
    volumes:
      - .:/rails
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/rails/node_modules
    working_dir: /rails
    depends_on:
      - web
volumes:
  bundle_data:
  postgres_data:
  node_modules: